### ISSUE TITLE
volume pretty low

### ISSUE THREAD

**Issue by Wiredframe** [cemrich/zapp#161] opened 2019-07-01 15:33 UTC
Compared to my other apps the volume seems to be pretty low in Zapp. Is there a chance that this could be fixed? Thanks! Really enjoy using this app. 👍

**Comment by cemrich** [comment] 2019-07-06 10:35
Can anybody confirm this issue?

@Wiredframe What device are you using an which Android version?

**Comment by userdimi** [comment] 2019-07-06 11:19
@cemrich I can't reproduce the issue. The volume is pretty good especially if you bumped up the volume by sliding up on the right side of the screen

**Comment by Wiredframe** [comment] 2019-07-06 11:38
I'm using a Galaxy S10e. I compared the volume of Spotify, Music Player and Zapp. Zapp had a lower volume compared to the others I think. But I could be wrong too. ^^

**Comment by cemrich** [comment] 2019-07-06 12:56
@Wiredframe @userdimi Thanks for the feedback!

**Comment by cemrich** [comment] 2019-07-09 18:40
I'll close this for now. Feel free to reopen if anybody is able to reproduce this issue.

**Closed by cemrich** 2019-07-09 18:40 UTC
Labels: feedback needed
