### ISSUE TITLE
V1.9.0 (23) mediathek fails on android 7.1.2 (lineage os 14.1) - Error Message: Das Gerät kann keine verschlüsselte Verbindung zum Server aufbauen.

### ISSUE THREAD

**Issue by axel1973** [cemrich/zapp#96] opened 2017-12-02 07:53 UTC
Using zapp V1.9.0 (23) on android 7.1.2 (lineage os 14.1)
Switching to mediathek view fails with Error Message: "Das Gerät kann keine verschlüsselte Verbindung zum Server aufbauen. ... "

Since there is no "in App" way to provide proper feedback/bug report including screenshots, logs and statistics up front, please ask for details and how to collect them , if required.

best regards
Axel

**Comment by jcgruenhage** [comment] 2017-12-02 08:09
Duplicate of #95

**Comment by cemrich** [comment] 2017-12-02 12:58
Yes, this issue is fixed in version 1.9.1 which F-Droids build server will hopefully pick up soon...

**Closed by cemrich** 2017-12-02 12:58 UTC
