### ISSUE TITLE
Streaming of ARD ONE, NDR and MDR Sachsen does not work

### ISSUE THREAD

**Issue by rojoweko** [cemrich/zapp#88] opened 2017-11-12 20:04 UTC
The Streams of ARD ONE, MDR Sachsen and all NDR flavours do not work and the error message "Das Video konnte nicht geladen werden. Vielleicht besteht keine Internet-Verbindung oder das Video ist in deinem Land nicht verfügbar." is shown instead after a couple of seconds. This behaviour has been checked for the foss-versions 1.8.1, 1.8.0 and 1,7,2.

**Comment by rojoweko** [comment] 2017-11-12 20:12
I checked this via DSL and mobile Internet in Berlin on two phones and had a second person in Bavaria try this as well with the same result.

Do you need any further information?

Thanks in advance!

**Comment by cemrich** [comment] 2017-11-13 19:31
Thank you very much for your report! I cannot reproduce this issue on my devices. Most likely your device or your Android version is too old to handle the stream. On which Android version(s) and which device(s) did the error occur?

**Comment by rojoweko** [comment] 2017-11-13 19:54
This has been tested on two Samsung Galaxy A3 (2017) with Android 7.0 and a Samsung Galaxy A3 (2015) with Android 6.0.1. The error occured on each device with said versions, but used to work before (on the 2015 A3). All other streams work fine though.

**Comment by cemrich** [comment] 2017-11-14 12:58
All right, I can reproduce the issue. Hopefully I can fix this the next days.

**Comment by cemrich** [comment] 2017-11-14 15:31
A fix will will be released the next few days with version 1.9.0.

**Comment by rojoweko** [comment] 2017-11-15 10:14
Awesome! Thanks a lot for all your great work! ;-)

**Comment by rojoweko** [comment] 2017-11-19 19:38
I checked the streams now. ARD One and NDR work alright, but the MDR streams (at least Sachsen and Sachsen Anhalt) cause trouble now and show the same error message.

**Comment by cemrich** [comment] 2017-11-22 16:17
Okay, that's very weird. All streams you mentioned do work on my device with a fresh install of 1.9.0 from fdroid.

**Comment by rojoweko** [comment] 2017-11-22 18:03
I checked this after deleting all Zapp data in the Android settings (should have the same effect as a fresh install) via mobile network in Jena and had someone else with an identical phone (Galaxy A3 2017) try it also in southern Germany via cable internet. I will check again in Berlin when I get there. Could it be another problem with the URLs? Where do I find the URLs? Is there another way of testing these?

**Comment by rojoweko** [comment] 2017-11-22 18:14
Never Mind! I just did a real fresh install - and everything appears to be working just fine! ;-) Sorry for the false report and thanks a lot for your quick reaction! You can close this issue again. ;-)

**Comment by cemrich** [comment] 2017-11-22 20:42
Wow, it is weird that the old urls survived an app update. For future reference: you can find the urls an channel names at https://github.com/cemrich/zapp/blob/master/app/src/main/res/raw/channels.json

**Closed by cemrich** 2017-11-22 20:42 UTC
Labels: bug
